"""Download compact leakage-safe CFB matchup-line datasets.

These files are generated by sportsdataverse/cfbfastR-cfb-data. They contain
pregame/as-of team features. Raw files stay under runtime/ and are not committed.
"""
from __future__ import annotations
import argparse
from pathlib import Path
from urllib.request import urlretrieve

BASE = "https://github.com/sportsdataverse/sportsdataverse-data/releases/download/cfb_matchup_line"

def download(season: int, out_dir: Path, force: bool = False) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    dest = out_dir / f"cfb_matchup_line_{season}.csv"
    if dest.exists() and not force:
        print(f"exists: {dest}")
        return dest
    url = f"{BASE}/cfb_matchup_line_{season}.csv"
    print(f"downloading {season}")
    urlretrieve(url, dest)
    print(f"saved: {dest}")
    return dest

def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("seasons", nargs="*", type=int, default=list(range(2015, 2027)))
    p.add_argument("--out-dir", default="runtime/cfb/matchup_line")
    p.add_argument("--force", action="store_true")
    args = p.parse_args()
    for season in args.seasons:
        download(season, Path(args.out_dir), args.force)

if __name__ == "__main__":
    main()
